eslint/markdown

- .editorconfig
- .travis.yml
- Disable build notification emails.
- Move `npm link` from `script` to `install` where it belongs.
> Build: Update Travis config (fixes #20)

- lib/processor.js
- package.json
- tests/processor.js
> Update: Use remark for parsing (fixes #38)

- lib/processor.js
- package.json
> Bump remark to v5

- tests/lib/processor.js
🚧  ~~This depends on #63, which should be merged first, and then I'll update the base branch for this PR back to `master`.~~ 🚧  *Edit: Done*
> Chore: Increase code coverage

- package.json
Looks like this line was mistakenly removed in the shuffling in #63.
> Build: Install eslint-release

- tests/lib/plugin.js
> Chore: Add test ensuring config comments do not fall through

- tests/lib/processor.js
> Chore: Add test for code fences without blank lines

- .travis.yml
I'm also going to investigate using GitHub Actions (initially in parallel to this, eventually replacing Travis if things go well), but I wanted to get this in first since it's long overdue.
> Chore: Add Node 12 to Travis

- .github/workflows/ci.yml
I'd like to run this in parallel with Travis for a bit, but given how often I'm having to manually restart Travis builds for unrelated failures, that may not be too long.
> Chore: Use GitHub Actions

- .eslintignore
- index.js
- package.json
- tests/lib/processor.js
Chore: Remove call to lint absent `Makefile.js`
In the process, add to the ignore file to explicitly exclude undesired; also lint additional file
> Chore: Remove call to lint absent `Makefile.js`

- .github/workflows/ci.yml
> ci: update GitHub actions

- .github/workflows/ci.yml
- package.json
Refers https://github.com/eslint/eslint/issues/14827
This updates the names of the scripts in package.json to be consistent with the [new standard](https://eslint.org/docs/latest/contribute/package-json-conventions).
We may need to update the `release` related scripts on Jenkins before merging this PR.
> chore: standardize npm script names

- eslint.config.js
- package.json
Switches to using eslint v9 and eslint-config-eslint v10 to lint this project.
> chore: switch to eslint v9, eslint-config-eslint v10

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- jsr.json
- package.json
- release-please-config.json
Creates a JSR package for `@eslint/markdown`:
- Added `jsr.json`
- Added JSR publish to `release-please.yml`
- Added JSR test to `ci.yml`
Refs #260
> feat: JSR package

- docs/rules/no-html.md
Hello,
I've fixed inaccurate description in `no-html.md`. 
It looks like this description was mistakenly copied from `no-empty-links`.
> docs: fix inaccurate description in `no-html.md`

- eslint.config.js
- package.json
Hello,
I've updated ESLint config file to use `defineConfig`, and I also bumped ESLint to the latest version.
Added `defineConfig` to `eslint.config.js` and bumped ESLint to latest version.
> chore: update ESLint config file to use `defineConfig`

- .github/workflows/bun-test.yml
Hello,
I've added a CI test for `bun`.
This workflow file exists in both the [`css`](https://github.com/eslint/css/blob/main/.github/workflows/bun-test.yml) and [`json`](https://github.com/eslint/json/blob/main/.github/workflows/bun-test.yml) repositories, but it was missing from `markdown`.
I've added a CI test for `bun` using GitHub Actions.
> ci: add test for `bun`

- README.md
Clarify that this both lints and processes.
Adds a few words to the README.md description to indicate linting.
Fixes #372.
> docs: update README.md to mention linting Markdown

- docs/rules/fenced-code-language.md
- docs/rules/heading-increment.md
- docs/rules/no-html.md
Hello,
While reading the document, I found and fixed some typos.
> docs: fix some typos

- src/index.js
- tests/package/exports.test.js
In this PR, I've exported `MarkdownLanguage` from `index.js`.
This PR resolves #533
In this PR, I've exported `MarkdownLanguage` from `index.js`.
Closes: #533
N/A
> feat: export `MarkdownLanguage` from `index.js`
