eslint/markdown

lib/processor.js, test/processor.js
This is a rough, non-unit-tested cut at preventing some error messages from being reported by the plugin.
To keep a message from being reported:
* The message must be placed on the same line that ESLint would report the error on.
* The message must be in multiline comment format (`/* */`)
* The message must start with `error`
* Multiple messages can be used on the same line.  Each must follow the format above.
* The message must match the message *as reported*, not necessarily as displayed.  For instance, the stylish reporter seems to strip trailing full stops (`.`).  Some flexibility should probably be added to the check in this regard.
I'm not terribly happy with the implementation of `getUnexpectedMessages()`, and I would love to know a better way to accomplish omitting messages which …
=> New: Filter out expected errors (fixes #4)

lib/processor.js, test/processor.js
http://spec.commonmark.org/0.21/#fenced-code-blocks
- Anything indented >4 spaces is considered an indented code block
- Code fences may be indented by 0 to 3 spaces
- Lines are unindented up to the level of the opening fence
- Fences may have backticks (`) or tildes (~)
- Fences may consist of >= 3 characters
- Closing fences must be at least as long as the opening fence
- Opening fence info strings may contain everything except backticks
- Whitespace around opening fence info strings is ignored
- Closing fences may be followed by whitespace but nothing else
@IanVS how's this?
=> Breaking: CommonMark-compatible code fences (fixes #2)

.eslintrc, index.js, lib/index.js, lib/processor.js, package.json, test/processor.js
This copies the `.eslintrc` from `eslint@1.2.1` with the only addition being this plugin itself.
@nzakas are there any more code style differences that this doesn't fix yet?
=> Upgrade: ESLint v1

lib/processor.js, test/processor.js
Allows expected errors to be provided as line comments, as well as block comments.
@btmills, I'm not particularly happy with the regex, but it does seem to work.  Can you please review?
=> Update: Allow line comments for expected errors (fixes #12)

lib/processor.js
I realized we already had the text of the current line, so there was no need to regenerate it with the `split()`. Now the error checking only runs when a line of code is found, and it only checks mode once.
=> Update: Optimize expected error checking (fixes #16)

package.json
This will pull in the changes to `eslint-config-eslint` from eslint/eslint#4910, which requires `eslint@2`. Updated `object-assign` as well to clean up `npm outdated` output.
=> Upgrade: Dependencies (fixes #40)

README.md, lib/processor.js, tests/plugin.js, tests/processor.js
=> Fix: Exclude eol-last from output (fixes #48)

README.md, lib/processor.js, package.json, tests/fixtures/long.md, tests/plugin.js, tests/processor.js
Initially, #46 was about adding custom syntax and logic into the processor to support configuration comments. The plugin would permit disabling ESLint or specific rules for entire code blocks, and all of that would be done in the plugin. Eventually, #54 would support configuring rule options.
I realized while working on #46 that custom syntax is unnecessary and overly complex when ESLint already has built-in support for configuration comments! With this change, when the plugin sees an HTML comment preceding a code block, it converts the comment's body into a JS block comment at the beginning of the source code. If it's an ESLint config comment, ESLint will pick up on it.
This example enables the browser environment, disables the no-alert rule, and configures the quotes rule to prefer …
=> Update: Support configuration comments (fixes #46, fixes #54)

package.json
`eslint-release` expects `pkg.files` to be an array of relative paths without any globs.
`lib/.eslintrc.yml` shouldn't be included in the bundle, so it's necessary to specify individual paths instead of just `lib`.
=> Build: Explicitly specify package.json files

.eslintrc.js, lib/.eslintrc.yml, tests/.eslintrc.yml
These rules were originally disabled when the README contained JS code fences that were getting linted. That's no longer the case, so we don't need to override `eslint-config-eslint` anymore.
=> Chore: Un-disable strict and eol-last in repository

README.md, lib/processor.js, tests/lib/processor.js
```js
{
// This code block is hidden from ESLint.
"hello": "world"
}
```
```js
console.log("This code block is linted normally.");
```
=> New: Custom eslint-skip HTML comment skips blocks (fixes #69)

lib/processor.js, tests/fixtures/long.md, tests/lib/plugin.js
=> feat: support globals

README.md
Just a docs update, this was previously implemented in e34acc60.
=> Docs: Add unicode-bom to list of unsatisfiable rules

package.json
This brings in @not-an-aardvark's eslint/eslint-release#20 so that release notes get published as a GitHub release.
=> Build: Upgrade to eslint-release@0.11.1

CONTRIBUTING.md
Howdy! 👋 
Was looking at contributing to the project but the CLA link in CONTRIBUTING.md wasn't loading. This update looks like the right one.
Thank you!
=> Docs: Updating CLA link

lib/processor.js, package.json, tests/lib/plugin.js, tests/lib/processor.js
Fixes #87
This adds each blocks `start.line` to each message's `endLine`, if it exists on the message.
~~This PR also updates the `eslint` used in tests to version 4. The older version of eslint did not emit `endLine` numbers.~~
=> Fix: Emit correct endLine numbers

README.md, lib/processor.js, package.json, tests/lib/plugin.js, tests/lib/processor.js
=> New: Enable autofix (--fix)

README.md
Fixes #109
- Docs: Mention general applicability of `overrides` (and put the `strict` discussion as a subsection)
- Docs: Add tips for working with Atom linter-eslint
=> Docs: `overrides` and Atom linter-eslint tips

lib/index.js, lib/processor.js, package.json, tests/lib/plugin.js, tests/lib/processor.js
The prior config was still enforcing ES5 coding standards. The earliest supported version of Node.js is 6.14.0, so this lets us use all the nice ES6 features.
I split this into multiple commits to ease review:
- b90a6d6 is just `npm install`ing the right versions.
- 02ce704 was done entirely with `npm run lint -- --fix`.
- 24fb9b7 was a bulk find replace `assert.equal` to `assert.strictEqual`.
- 6ca28b5 narrowed variable declaration scope where possible.
- 2612d95 took advantage of the array spread operator.
=> Chore: Upgrade to eslint-config-eslint@5.0.1

README.md
Puts Markdown examples within (quadruple-backtick) fenced blocks
=> Syntax highlight Markdown

lib/processor.js, tests/lib/plugin.js
Previously, if a rule added an autofix at index 0 of a code block, all
code from the start of the markdown file until the start of that code
block would be removed. Now, the autofix is applied as expected.
Fixes lydell/eslint-plugin-simple-import-sort#22
=> Fix: Support autofix at the very start of blocks

lib/processor.js, tests/lib/plugin.js
Thanks to @lydell for discovering this bug and writing the tests to reproduce it in #120.
If I lint the following Markdown source text containing a JS code block inside a blockquote:
````md
This is Markdown.
>   ```js
>   console.log('Hello, \
>   world!');
>   ```
````
What ESLint sees is this:
```js
console.log('Hello, \
world!');
```
The fix text sent to the processor will contain the string, now with double quotes, and preserving the newline as-is:
```
"Hello, \\\nworld!"
```
The fix would then be applied incorrectly because it didn't account for the leading `>   ` in the Markdown source text:
````md
This is Markdown.
>   ```js
>   console.log("Hello, \
world!" world!');
>   ```
````
This change tracks the leading text that precedes the first line of any fenced code block and inserts …
=> Fix: Indent multiline fixes (fixes #120)

.gitignore, package.json, tests/lib/plugin.js
Upgrade: Update devDeps and change istanbul -> nyc
Update eslint-release, chai, mocha, eslint devDeps. In process of updating,
get plugins tests to work in anticipation of eslint 6.
Note that this still doesn't include logic to exclude ESLint 6 in Node 6 on Travis (or, if you preferred, to bump `engines` to 8.10.0 and drop Travis testing of 6).
If you like, I can also upgrade the deps. to the versions prior to breaking.
=> Upgrade: Update devDeps and change istanbul -> nyc

README.md
No need to have all the badges on eslint/eslint, but npm version and build status are handy.
=> Chore: Add npm version and build status badges

.eslintrc.js, lib/processor.js, package.json
This syntax first shipped in Node.js v8.6.0 and removes a dependency on `object-assign`.
=> Chore: Use ES2018 object spread syntax

package.json
The new processor API shipped in ESLint v6.
Is there any reason the peer dependency would cause trouble? It was removed back in #40 because it had issues with a prerelease. npm doesn't consider `v7.0.0-alpha.1` to satisfy `>=6.0.0`, but if I install `eslint@7.0.0-alpha.1` on top of this commit, I get a warning that the `eslint@>=6.0.0` peer dependency is unmet, yet it doesn't appear to break anything.
=> Breaking: Require ESLint v6

lib/processor.js, package.json
This matches ESLint configuration as of the last v6 release. Since this only affects devDependencies, it's a chore rather than an upgrade tag.
`require-unicode-regexp` was the only rule that required code changes.
=> Chore: Update ESLint config and plugins

lib/processor.js, tests/lib/plugin.js
Issue #112 reported VSCode drawing squigglies all the way from the top of a file to a line in a code block with a syntax error rather than just squigglying the line with the syntax error. For messages that only specified start locations, the processor was adding `endLine: NaN`.
=> Fix: Don't require message end locations (fixes #112)

README.md, index.js, lib/index.js, tests/fixtures/recommended.json, tests/lib/plugin.js
Should `plugin:markdown/recommended` enable the processor on just `.md` files or also `.mkdn`, `.mdown`, and `.markdown` (the same file extensions as v1)? I went with just `.md` since overriding to add the other extensions is straightforward, but I could be convinced to include the other three.
Is test coverage adequate? I My thinking was that asserting "it works" is sufficient to say the recommended config is being loaded, and the rest of the plugin tests can handle the details.
=> New: Add recommended config (fixes #151)

.github/workflows/ci.yml
Noticed we aren't running CI in Node 14!
=> Chore: run CI in Node 14.x

lib/index.js
It's basically what documentation suggests. One rule I would add, but in documentation only, is `"import/no-unresolved": "off"`
=> New: Add recommended config

README.md, lib/index.js
#157 took the rules that the documentation already recommended disabling and quite sensibly added them to the `plugin:markdown/recommended` config, and I've updated the docs accordingly, including a helpful note about plugin rules as suggested by @arvigeus in #157.
You can skip reviewing the first commit, 0b1a905accd82d20149e626e76cf1046dc2bac48, because it's a cut-and-paste rearrangement to make the diff in the next commit easier to review. The bulk of the change is in d08afa1fe9ab38f811b6ea44176eff838c5f0023.
=> Docs: Reference recommended config disabled rules

.github/workflows/ci.yml, package.json
The 2.0.0-rc.0 release attempt failed when trying to run the examples' tests because their dependencies were never installed. In #152, I added an install step to the GitHub Actions workflow but not the Jenkins release flow. This change adds an `install-examples` npm script and calls it both from the GitHub Actions workflow and the `generate-.*release` scripts.
=> Build: Install example test dependencies in Jenkins

.github/workflows/ci.yml, package.json
Previously, CI was explicitly running the `install-examples` script as its own step. This was also necessary but not documented locally, so `git clone; npm install; npm test` would show a couple failures when the examples inherited the wrong ESLint dependency. The examples' dependencies should now be installed automatically when running `npm install` locally without any arguments.
Originally reported in #163.
**For reviewers:** Based on my reading of https://docs.npmjs.com/cli/v6/using-npm/scripts, this is a safe usage of the `prepare` script, but I'd appreciate a second set of eyes on that. The goal is to run as part of `npm install` locally but not when the plugin is a dependency. The additional runs before packing and publishing are unnecessary but I don't think they should cause a …
=> Chore: Automatically install example dependencies

.github/workflows/ci.yml, README.md, package.json
The only remaining string search results for "master" are URLs to other repositories.
=> Chore: Switch to main for primary branch (fixes #161)

lib/processor.js, tests/lib/processor.js
This was working correctly in v1 but stopped working when v2 switched to the new processor API. The generated filename was `0.js more words are ignored`. The test case for this was insufficiently strict: it asserted that the code block was extracted, which was sufficient with hard-coded extensions in v1, but it didn't assert the generated name was `0.js` now that we're taking the extension from the info string.
Per [CommonMark 0.29]:
> The line with the opening code fence may optionally contain some text following the code fence; this is trimmed of leading and trailing whitespace and called the info string.
I've strengthened the tests for generated filename extensions and added a new test to ensure that leading whitespace is trimmed correctly.
[CommonMark 0.29]: …
=> Fix: Ignore words in info string after syntax (fixes #166)

.github/workflows/ci.yml, npm-prepare.js, package.json, tests/lib/plugin.js
#166 originally reported being unable to `npm install` in the repository on Windows. This was due to the changes in #164, which worked fine on Linux and macOS but not Windows. This PR first adds macOS and Windows to the test matrix and then fixes the npm prepare script by moving the previous bash-only logic into JS.
=> Fix: npm prepare script on Windows (refs #166)

lib/index.js, tests/fixtures/recommended.json, tests/lib/plugin.js
I think this configuration had no effect on code blocks as it was an override for `*.md`, and that it should be instead an override for virtual filenames under `*.md/`.
=> Fix: overrides pattern for virtual filenames in recommended config

README.md
I plan to release v2.0.0 this weekend, so these prerelease-specific notes can finally be removed from the README!
=> Docs: Remove prerelease README notes

lib/processor.js, tests/lib/processor.js
Comment attachment was sensitive to whitespace around the code block and preceding comments. In some cases, the parser would place comments as descendants of code blocks' preceding sibling nodes. However, a depth-first traversal of the tree will still encounter the comments in linear order, which is sufficient for our purposes. This approach no longer traverses backwards from code blocks looking for preceding comments, so we no longer need to pass the `parent` node and index into its children.
=> Fix: More reliable comment attachment (fixes #76)

.gitignore
https://github.com/eslint/eslint-plugin-markdown/pull/182#discussion_r603764071
=> Chore: add yarn.lock and package-lock.json into .gitignore just like eslint/eslint

package.json, tests/lib/plugin.js, tests/lib/processor.js
[`remark-parse@7.0.0`](https://github.com/remarkjs/remark/releases/tag/remark-parse%407.0.0) includes https://github.com/remarkjs/remark/pull/423, which fixes handling of leading and trailing newlines in fenced code blocks.
**For reviewers:**
1. `remark-parse` v6, v7, and v8 were semver-major fixes. v9 was a full rewrite. Are we comfortable with a parser major version bump in a semver-minor release? This is currently tagged as `Update:` so it's semver-minor rather than semver-patch.
2. If so, how far? This PR bumps to v7 because it fixes two known issues, #77 and #78. I'm not aware of any `eslint-plugin-markdown` issues that would be fixed by v8 or v9.
3. If we're fine upgrading past v7 for speculative parsing accuracy improvements that don't knowingly affect `eslint-plugin-markdown`, …
=> Update: Upgrade remark-parse to v7 (fixes #77, fixes #78)

lib/processor.js, package.json, tests/lib/plugin.js, tests/lib/processor.js
The previous parser, `remark-parse` v7, included a transitive dependency on an npm package with a security vulnerability (see #186). Newer versions of `remark-parse` are wrappers around a new underlying parser, `mdast-util-from-markdown`, so [we can use that directly](https://github.com/eslint/eslint-plugin-markdown/pull/175#issuecomment-821969970).
I [had thought](https://github.com/eslint/eslint-plugin-markdown/pull/171#issuecomment-826390279) the upgrade was going to be more difficult because the new parser no longer supplies per-line indent information, but we're already calculating it in `getBlockRangeMap()`, so I included the indentation in the each line's `RangeMap` and read from there instead.
The previous parser also failed to preserve `\r\n` line endings, replacing them all with …
=> Update: Replace Markdown parser (fixes #125, fixes #186)

lib/processor.js, tests/examples/all.js, tests/lib/processor.js
related https://github.com/mdx-js/eslint-mdx/issues/339#issuecomment-906350368
cc @btmills
=> Fix: `message.line` could be `undefined`

.github/workflows/ci.yml
CI-related change.
updated setup-node action to v2 for CI node workflow.
https://github.com/marketplace/actions/setup-node-js-environment
=> Chore: use `actions/setup-node@v2` in CI

.gitignore
Ignore `pnpm-lock.yaml` for `pnpm` users. We already ignore `package-lock.json` and `yarn.lock`.
=> Chore: ignore `pnpm-lock.yaml`

.github/workflows/ci.yml
As asked by @btmills in https://github.com/eslint/eslint-plugin-markdown/pull/195#issuecomment-955802046
=> chore: test all supported ESLint versions

.eslintrc.js, package.json
As asked by @btmills in https://github.com/eslint/eslint-plugin-markdown/pull/195#issuecomment-955802046
=> chore: update `devDependencies`

tests/lib/plugin.js
As asked by @btmills in https://github.com/eslint/eslint-plugin-markdown/pull/195#issuecomment-955802046
=> test: test with `ESLint` instead of `CLIEngine` when available

npm-prepare.js, tests/examples/all.js
Previously, OS-created hidden files like `.DS_Store` in `examples/` would cause the prepare and test scripts to throw `ENOTDIR`. They now filter for directories that contain a `package.json` before installing dependencies or running tests.
=> chore: Check for package.json in examples

.github/workflows/ci.yml, package.json
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉
devDependency compatibility with ESLint 8:
---
Closes #194
=> chore: add tests for ESLint 8

examples/react/eslint.config.js, examples/react/package.json
Since the react test example uses eslint-plugin-react's flat config export, `@eslint/eslintrc` is unused in that test project.
=> chore: remove unused `@eslint/eslintrc` in test examples

examples/typescript/README.md, examples/typescript/eslint.config.js, examples/typescript/package.json
Updates examples/typescript test project to use the new package [`typescript-eslint`](https://www.npmjs.com/package/typescript-eslint) that supports flat config.
Note that `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` are dependencies of `typescript-eslint` so there's no need to install them separately.
Configuration in eslint.config.js is based on the first example from https://typescript-eslint.io/linting/configs.
=> test: use latest `typescript-eslint` in examples

lib/index.js, lib/processor.js, tests/lib/plugin.js, tests/lib/processor.js
Adds `meta` property to the plugin object and the processor object, for serialization purposes.
With this config:
```js
// eslint.config.js
import markdown from "eslint-plugin-markdown";
export default [
{
files: ["**/*.md"],
plugins: { markdown },
processor: "markdown/markdown"
}
];
```
`eslint --print-config foo.md` will print:
```
{
"languageOptions": {
"ecmaVersion": "latest",
"sourceType": "module",
"parser": "espree@9.6.1",
"parserOptions": {},
"globals": {}
},
"processor": "markdown/markdown",
"plugins": [
"@",
"markdown:eslint-plugin-markdown@3.0.1"
],
"rules": {}
}
```
With this config (processor is used directly):
```js
// eslint.config.js
import markdown from "eslint-plugin-markdown";
export default [
{
files: ["**/*.md"],
processor: markdown.processors.markdown
}
];
``` …
=> feat: add `meta` property

.gitignore
Adds `.vscode` to `.gitignore`, as in other repos, so that contributors can change their VS Code settings without these files being marked as changed. Particularly useful at the moment since `eslint.experimental.useFlatConfig` should be enabled in vscode-eslint settings.
=> chore: add `.vscode` to `.gitignore`

examples/react/README.md
Fixes `examples/react/README.md`, the part with expected errors. This plugin's `recommended` config disables the `no-unused-var` rule, so errors for this rule don't appear when linting the react example project.
https://github.com/eslint/eslint-plugin-markdown/blob/cbb8e3afc665d314570a9b087c7cef2e97d45860/lib/index.js#L21
=> docs: fix expected errors in react example

.github/workflows/release-please.yml
Updates the `release-please` workflow to use `actions/checkout@v4` and `actions/setup-node@v4`.
The only breaking change in both is that the action itself runs in Node 20 instead of Node 16.
=> chore: bump setup-node and checkout actions to v4 in release workflow

lib/processor.js, tests/lib/processor.js
Fixes #244.
Added an upper guard to make sure the access to `block.rangeMap[lineNumber]` is defined as well as add a simple test case (I manually set the state via `preprocess` in the test case and not use the "shared" state from the beforeEach to make this test case clearer).
=> fix: check upper bounds of message line numbers for code blocks

README.md, eslint.config.js, lib/processor.js, tests/lib/processor.js
Fixes #245.
I researched common language codes for javascript and markdown which are not the same as the file extension.
There may be additional ones.
The current tests had test cases for the language codes `javascript` and `node` already, so I adjusted them and added a case to make sure the mapping from code block language to file extension is done after the code block language normalization.
This may be a breaking change as additional code blocks may be linted.
=> feat!: map known code block languages to respective file extensions

.github/workflows/ci.yml
Adds Node 22 and ESLint v9 to test matrix.
=> ci: run tests in Node.js 22, with ESLint 9

eslint.config.js, npm-prepare.js, package.json, tests/lib/plugin.js
Switches to eslint-config-eslint v11
=> chore: switch to eslint-config-eslint v11

lib/index.js
Adding names to configs makes them easier to check with @eslint/config-inspector.
=> feat: add name to flat configs

release-please-config.json
Trying to fix release-please so it creates a tag name without a component.
=> build: Fix release-please tag name

examples/react/README.md, examples/react/eslint.config.mjs, examples/react/package.json, examples/typescript/README.md, examples/typescript/eslint.config.mjs, examples/typescript/package.json, tests/examples/all.test.js
This PR updates test examples (react and typescript) to use ESLint v9. Since this plugin now supports only ESLint >=9, it doesn't make sense to test with ESLint v8.
=> test: use ESLint v9 in examples

.gitignore, package.json, rollup.config.js, src/index.js, src/processor.js, src/types.ts, tools/dedupe-types.js, tsconfig.esm.json, tsconfig.json
This adds TypeScript into the project:
- Added type definitions to validate the code
- Generated type definitions for the package
- Added Rollup to create a single file to distribute
=> feat: Add type checking and type definitions

package.json
Closes https://github.com/eslint/markdown/issues/278
Based on the Node.js docs ([link](https://nodejs.org/api/packages.html#conditional-exports)), I can't say for sure that the existing `exports` field is invalid, but it is certainly uncommon, which might be the issue behind #278. I updated the `exports` field to a more common format as described in the Node.js docs, and based on my testing, it does fix #278.
=> fix: correct `exports` field in package.json

eslint.config.js, package.json, src/language/markdown-source-code.js
This refactors the plugin to use `@eslint/plugin-kit`, allowing us to remove a bunch of code.
=> refactor: Use @eslint/plugin-kit

src/processor.js, tests/processor.test.js
The processor doesn't account for BOM, which would be passed in by ESLint if the file has it.
This causes incorrect adjustments of locations and fix ranges.
Repro: https://github.com/mdjermanovic/eslint-markdown-bom
In the above repro, `space-in-parens` rule fixes `( a)` to `( )` instead of `(a)`.
This PR updates `preprocess()` to remove BOM from the text it operates on.
=> fix: Account for BOM in the processor

README.md
Fixes an example in README by adding `language` key, without which the configuration wouldn't work as expected.
=> docs: Fix example with individually configured rules

README.md, package.json, src/language/markdown-source-code.js, src/rules/no-html.js, tests/language/markdown-source-code.test.js, tests/plugin.test.js, tests/rules/no-html.test.js
This PR adds support for disable comments to the Markdown plugin. It supports all of the variations that ESLint supports:
- `eslint-disable`/`eslint-enable`
- `eslint-disable-line`
- `eslint-disable-next-line`
While working on this, I discovered a bug in `no-html` where it was only reporting the first HTML tag in an `html` node even though there can be multiple. It was also skipping any `html` node that began with a comment. I also fixed these bugs in this PR, as I needed a good example to test the disable directives.
Note: This PR intentionally does not implement inline configuration comments like `/* eslint rule:error */`.
=> feat: Add disable comment support

src/language/markdown-language.js
Updated the JSDoc comments for the createSourceCode function to correctly refer to `MarkdownSourceCode` instead of `JSONSourceCode`.
=> chore: Update comments to correctly refer to MarkdownSourceCode

examples/typescript/package.json
Updates `examples/typescript` test project to use the latest `typescript-eslint` v8.x instead of a prerelease version.
=> test: Use latest `typescript-eslint` v8.x

package.json
This version of mdast-util-from-markdown upgrades
- micromark to 4.0.0
- unist-util-stringify-position to 4.0.0
=> chore: mdast-util-from-markdown ^2.0.2

README.md, eslint.config.js, package.json, src/rules/fenced-code-language.js, src/rules/heading-increment.js, src/rules/no-duplicate-headings.js, src/rules/no-empty-links.js, src/rules/no-html.js, src/rules/no-invalid-label-refs.js, src/rules/no-missing-label-refs.js
-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Enables `eslint-plugin-eslint-plugin` for linting rules and rule tests.
Added `eslint-plugin-eslint-plugin` dev dependency and enabled rules in the eslint config.
Also removed the ending dot from `meta.docs.description` in rules.
Config is the same as in eslint/json repo (https://github.com/eslint/json/pull/64).
=> chore: use eslint-plugin-eslint-plugin

examples/typescript/package.json
Unpins `eslint` in `examples/typescript` since the problem for which it was pinned in https://github.com/eslint/markdown/pull/302 has been resolved in `typescript-eslint` v8.15.0.
=> test: unpin `eslint` in `typescript-eslint` test

.github/workflows/ci.yml, package.json, src/index.js, tests/types/tsconfig.json, tests/types/types.test.ts, tools/build-rules.js
Because of type inference issues, only the `languages` property is currently included in the definitions for `plugin`:
```ts
/** @type {Plugin & { languages: Record<string,Language>}} */
declare const plugin: Plugin & {
languages: Record<string, Language>;
};
```
from https://unpkg.com/@eslint/markdown@6.2.1/dist/esm/index.d.ts
This PR refactors the `plugin` definition to ensure that all relevant properties of language plugins are included in the types. I also added type tests similar to eslint/json#61.
=> fix: add type tests

src/processor.js, tests/processor.test.js
This updates the processor to adjust suggestion fixes in the same way as autofixes.
Currently, with this example config:
```js
// eslint.config.js
import markdown from "@eslint/markdown";
export default [
{
files: ["**/*.md"],
plugins: {
markdown
},
processor: "markdown/markdown"
},
{
files: ["**/*.md/*.js"],
rules: {
"require-unicode-regexp": "error"
}
}
];
```
and this example code:
applying the "Add the 'u' flag" suggestion results in:
After this change, applying the suggestion will produce the correct result:
=> fix: adjust suggestion fix ranges in processor

.github/workflows/release-please.yml
This update the release process to post to Bluesky in addition to Mastodon and Twitter.
=> ci: Post to Bluesky on release

package.json, tests/types/tsconfig.json
This PR promotes `@eslint/core` to a runtime dependency and upgrades `@eslint/core` and `@eslint/plugin-kit` to the latest versions.
This change ensures that `@eslint/markdown` will be used with a compatible version of `@eslint/core` in dependent packages even if the core types are changed in a breaking way in the future. This will help avoiding bugs like #313 where the removal of a type from `@eslint/core@0.6.0` to `@eslint/core@0.10.0` was causing the TS build to fail. Since `@eslint/core` was defined in the devDependencies, npm would not check its version range when `@eslint/markdown` was itself installed as a dependency.
I also made a change to the `tsconfig.json` in the type tests because I noticed that some files in the `dist` directory were not being checked.
=> chore: upgrade `@eslint/core` and `@eslint/plugin-kit`

README.md, package.json, src/processor.js, src/types.ts, tests/fixtures/filename.md, tests/plugin.test.js, tests/processor.test.js
Fixes #226.
Per the RFC, does not include any name deduplication. That should already be done by ESLint itself.
=> feat: allow specifying filename in block meta

README.md
Removes Atom from the README as it has been deprecated.
fixes #321
=> docs: Remove Atom

tests/language/markdown-language.test.js
Hello,  
I've created basic test cases for `MarkdownLanguage`. This test was necessary to implement #325 correctly but was missing. I referenced tests for [JSON](https://github.com/eslint/json/blob/main/tests/languages/json-language.test.js) and [CSS](https://github.com/eslint/css/blob/main/tests/languages/css-language.test.js).  
I tried to create a failure case for the `parse()` method, but unlike JSON and CSS parsers, every string value is recognized as text. So, I couldn't make one fail. I'd appreciate it if you could suggest a possible failure case.
=> test: create tests for `MarkdownLanguage`

src/index.js, tests/types/types.test.ts
This PR exports the type definition for `MarkdownRuleDefinition`, making it accessible to consumers.
refs eslint/eslint#19521
=> feat: export `MarkdownRuleDefinition` type

src/language/markdown-source-code.js, tests/language/markdown-source-code.test.js
Hello,
I've finished implementing the `applyInlineConfig` method.
For both source code and tests, I referenced [JSON](https://github.com/eslint/json/blob/main/src/languages/json-source-code.js#L208-L250) and [CSS](https://github.com/eslint/css/blob/main/src/languages/css-source-code.js#L208-L250).
I also updated the `configCommentStart` regex to correctly recognize inline configs.
resolves: #330
=> feat: support `eslint` config comments

eslint.config.js, src/rules/fenced-code-language.js, src/rules/heading-increment.js, src/rules/no-duplicate-headings.js, src/rules/no-empty-links.js, src/rules/no-html.js, src/rules/no-invalid-label-refs.js, src/rules/no-missing-label-refs.js
to make it easier for consumers to access the documentation
enabled [the `eslint-plugin/require-meta-docs-url` rule](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-url.md) and ran the autofixer & autoformatter.
-
-
=> chore: add docs url to all rules

package.json
Hello,
Currently, `@eslint/markdown` relies on somewhat outdated `@eslint` dependencies.
As a result, I’m unable to use newly added features like those introduced in https://github.com/eslint/rewrite/pull/156 and https://github.com/eslint/rewrite/pull/173, since the plugin is still using the `0.x` versions.
Because version `0.10.0` with a caret (`^`) only allows updates up to but not including `0.11.0`, it causes inconsistencies when I try to use the newer types in `@eslint/markdown` and `@eslint/core`.
I've updated `@eslint/core` and `@eslint/plugin-kit` to the latest versions!
Technically, updating `@eslint/plugin-kit` wasn't necessary—but I went ahead and bumped it as well for consistency.
=> chore: bump `@eslint/core` and `@eslint/plugin-kit` to latest

tests/language/markdown-language.test.js
Hello,
I've corrected `path` typos in `markdown-language.test.js`.
Sorry I missed changing the `path` to `.md` earlier.
=> test: correct `path` typos in `markdown-language.test.js`

src/rules/no-missing-label-refs.js, tests/rules/no-missing-label-refs.test.js
Hello, 
I've fixed https://github.com/eslint/markdown/issues/346.
I added negative lookbehind `(?<!\\)` to the regex to properly escape `[` and `]`, and also added some tests.
fix: #346
=> fix: `no-missing-label-refs` rule does not respect escaping

package.json, tests/examples/all.test.js, tests/plugin.test.js, tests/processor.test.js
To reduce the project's dependency footprint by replacing the chai assertion library with node.js built-in assert module. This change maintains the same test coverage and functionality while removing an external dependency.
- Replaced chai imports with node.js assert in all test files.
- Updated assertion syntax to use node.js assert equivalents.
Fixes #350
=> chore: replace chai with node.js assert

package.json, src/language/markdown-source-code.js, src/types.ts, tests/types/types.test.ts
This pull request updates `MarkdownSourceCode` to extend `TextSourceCodeBase`
- Upgraded @eslint/core and @eslint/plugin-kit to latest versions
- Switched `MarkdownSourceCode` to extend `TextSourceCodeBase`
=> refactor: switch MarkdownSourceCode to extend TextSourceCodeBase

.gitignore
Hello,
In this PR, I've added `*.code-workspace` to `.gitignore`.
The `*.code-workspace` file functions similarly to the `.vscode` folder and generally shouldn't be included in version control.
Actually, I'm personally using this file, and it often shows up as an unintentional change when committing, so I'd really appreciate it if this suggestion gets accepted!
Reference: https://code.visualstudio.com/docs/editing/workspaces/workspaces#_workspace-settings
=> chore: add `*.code-workspace` to `.gitignore`

README.md, docs/rules/no-empty-definitions.md, src/rules/no-empty-definitions.js, tests/rules/no-empty-definitions.test.js
This PR adds a new rule `no-empty-definitions` to prevent empty URL definitions
Added the `no-empty-definitions` rule that warns on empty URLs (<>) or empty fragment URLs (#), along with documentation and tests.
Closes #359
@lumirlumir About including `[foo]:` in the no-empty-definitions rule, I held off because a few weird things popped up when I looked closer.
Take these for example:
```markdown
[foo]:
[bar]:
```
You'd think that's two errors, right? But this actually one definition where foo is the label and the URL is [bar].
So, because of these quirks, I think we should do what remark-lint does and actually check the definition nodes themselves in the code. That way, we're looking at the real definitions and not just the text, which seems much more reliable.
=> feat: add no-empty-definitions rule

src/rules/no-invalid-label-refs.js, tests/rules/no-invalid-label-refs.test.js
Hello,
While looking into the `no-invalid-label-refs` rule, I came across an interesting bug.
For example, in the code below, the rule correctly reports the position of the `[ ]`:
However, what happens if I insert a `\\` into the sentence?
The error line shifts forward by one line every time I add a `\\`:
The cause of this bug is that when using `node.value`, the `\\` is interpreted as a single `\`. As a result, the reported position changes whenever I insert a `\\`.
To fix this, I replaced `node.value` with `context.sourceCode.getText(node)` so that the position can be accurately tracked.
=> fix: `no-invalid-label-refs` do not report correct position

docs/rules/fenced-code-language.md, docs/rules/heading-increment.md, docs/rules/no-duplicate-headings.md, docs/rules/no-empty-definitions.md, docs/rules/no-empty-images.md, docs/rules/no-empty-links.md, docs/rules/no-html.md, docs/rules/no-invalid-label-refs.md, docs/rules/no-missing-label-refs.md
Update examples to match the standard with core rules.
Mainly added the rule configuration comment inside the examples, I think it would be helpful later as well when we implement https://github.com/eslint/eslint/issues/18824 and also once the eslint playground supports these plugins.
=> docs: update examples for rules

src/rules/require-alt-text.js, tests/rules/require-alt-text.test.js
Hello,
In this PR, I've updated the `require-alt-text` rule to ignore commented-out images.
Currently, when I write a markdown document like the one below, it shows a false positive:
```md
```
=> fix: update `require-alt-text` rule to ignore commented images

README.md, docs/rules/table-column-count.md, src/rules/table-column-count.js, tests/rules/table-column-count.test.js
This PR adds a new rule `table-column-count` to disallow data rows in a [GitHub Flavored Markdown table](https://github.github.com/gfm/#tables-extension-) from having more cells than the header row
Added the `table-column-count` rule, along with documentation and tests.
fixes #389
=> feat: added new rule table-column-count

.github/workflows/ci-build-all-pm.yml
Hello,
In this PR, I've created `ci-build-all-pm.yml` workflow. 
This workflow would help improve the stability of this repository by testing various package managers.
I've referred to the workflow in the [`css`](https://github.com/eslint/css/blob/main/.github/workflows/ci-build-all-pm.yml) repository.
=> ci: create `ci-build-all-pm.yml`

docs/rules/no-duplicate-definitions.md, docs/rules/no-multiple-h1.md
Hello,
In this PR, I've fixed some minor typos in the documentation.
=> docs: fix minor typos

docs/rules/no-duplicate-headings.md, src/rules/no-duplicate-headings.js, tests/rules/no-duplicate-headings.test.js
This PR adds a new siblingsOnly option to the no-duplicate-headings rule to make it more flexible. Currently, the rule flags any duplicate headings in the entire document, which can be too restrictive in some cases. With this new option, users can configure the rule to only check for duplicate headings among siblings (headings at the same level under the same parent heading).
Added a new siblingsOnly boolean option to the rule's schema and refactored the implementation to track headings by level, resetting tracking when moving between levels when siblingsOnly is enabled. Updated documentation and added test cases for both ATX and setext-style headings to verify the new behavior.
Fixes #390
=> feat: add checkSiblingsOnly option to no-duplicate-headings rule

README.md, src/language/markdown-language.js, src/types.ts, tests/language/markdown-language.test.js, tests/types/types.test.ts
To add JSON frontmatter support using the VitePress-style format (--- delimiters) 
- Added JSON frontmatter parser configuration using --- delimiters
- Added tests
- Added types
Closes #404
=> feat: add JSON frontmatter support

tests/util.test.js
In this PR, I've added tests for the `findOffsets()` utility function.
I noticed that tests for `findOffsets()` were missing, so I added them.
=> test: add test for `findOffsets()` util

package.json
Hello,
In this PR, I’ve updated lint-staged to also run `git add README.md` when the rules change.
Currently, when the rules change, only the `npm run build:update-rules-docs` script runs, so users have to manually add the updated `README.md` to the Git.
This approach has been used in the CSS repository, as shown below:
https://github.com/eslint/css/blob/main/package.json#L57-L60
=> chore: update lint-staged to run `git add README.md` when rules change

README.md, docs/rules/no-bare-urls.md, src/rules/no-bare-urls.js, tests/rules/no-bare-urls.test.js
This PR implements the `no-bare-urls` rule to enforce proper URL formatting in Markdown documents. The rule ensures URLs are either wrapped in angle brackets (autolinks) or used with text (links), rather than being used as bare URLs.
Implemented the `no-bare-urls` rule, along with documentation and tests.
Fixes #399
=> feat: add no-bare-urls rule

tests/rules/fenced-code-language.test.js
In this PR, I've corrected indentation in `fenced-code-language` test cases.
Currently, template literal like below yields a [AST](https://explorer.eslint.org/#eslint-explorer=IntcInN0YXRlXCI6e1widG9vbFwiOlwiYXN0XCIsXCJjb2RlXCI6e1wiamF2YXNjcmlwdFwiOlwiLyoqXFxuICogVHlwZSBvciBwYXN0ZSBzb21lIEphdmFTY3JpcHQgaGVyZSB0byBsZWFybiBtb3JlIGFib3V0XFxuICogdGhlIHN0YXRpYyBhbmFseXNpcyB0aGF0IEVTTGludCBjYW4gZG8gZm9yIHlvdS5cXG4gKiBcXG4gKiBUaGUgdGhyZWUgdGFicyBhcmU6XFxuICogXFxuICogLSBBU1QgLSBUaGUgQWJzdHJhY3QgU3ludGF4IFRyZWUgb2YgdGhlIGNvZGUsIHdoaWNoIGNhblxcbiAqICAgYmUgdXNlZnVsIHRvIHVuZGVyc3RhbmQgdGhlIHN0cnVjdHVyZSBvZiB0aGUgY29kZS4gWW91XFxuICogICBjYW4gdmlldyB0aGlzIHN0cnVjdHVyZSBhcyBKU09OIG9yIGluIGEgdHJlZSBmb3JtYXQuXFxuICogLSBTY29wZSAtIFRoZSBzY29wZSBzdHJ1Y3R1cmUgb2YgdGhlIGNvZGUsIHdoaWNoIGNhbiBiZVxcbiAqICAgdXNlZnVs …
=> test: correct indentation in `fenced-code-language` test cases

src/rules/no-duplicate-headings.js, tests/rules/no-duplicate-headings.test.js
This PR is a follow-up to [#421](https://github.com/eslint/markdown/pull/421).
I’ve updated the `no-duplicate-headings` rule to align with the CommonMark specification.
According to CommonMark, only space (` `) and tab (`\t`) characters are considered valid whitespace for `Heading` nodes.
However, the current implementation of `no-duplicate-headings` automatically removes whitespace characters like NBSP, which can lead to unintended behavior that doesn’t conform to the CommonMark spec. This may cause confusion for users who intentionally use NBSP characters, especially those using the closing-style ATX headings.
Here's a brief example with NBSP:
[AST with NBSP](https://explorer.eslint.org/#eslint-explorer=IntcInN0YXRlXCI6e1widG9vbFwiOlwiYXN0XCIsXCJjb2RlXCI6e1wiamF2YXNjcmlwdFwiOlwiLyoqXFxuI …
=> fix: update `no-duplicate-headings` to align with CommonMark spec

docs/rules/no-missing-link-fragments.md, src/rules/no-missing-link-fragments.js, tests/rules/no-missing-link-fragments.test.js
This PR fixes the handling of heading slugs in the no-missing-link-fragments rule to ensure that HTML nodes are excluded from the generated anchor fragments.
Updated the heading text extraction logic in no-missing-link-fragments to skip HTML nodes when generating slugs for headings.
Fixes #439
=> fix: skip HTML nodes in heading slugs for no-missing-link-fragments

src/rules/no-missing-link-fragments.js, tests/rules/no-missing-link-fragments.test.js
Hello,
In this PR, I've fixed case-insensitive attribute checks in `no-missing-link-fragment`.
According to the HTML specification, HTML attributes should be case-insensitive.
https://html.spec.whatwg.org/multipage/syntax.html#writing
I've fixed case-insensitive checks for attributes in `no-missing-link-fragment` and added some test cases.
=> fix: case-insensitive attribute checks in `no-missing-link-fragment`

src/types.ts
Hello,
While reviewing the `types.ts` file, I noticed that `Message` and `RuleType` are not used anywhere.
It seems these two types were not removed during the refactor.
I think removing unused types would be helpful, but I'm not sure if this should be considered a breaking change, since users can import types from `types.ts` via `@eslint/markdown/types`, and version 7 was just released.
On the other hand, since these types were likely included by mistake during a refactor, it might make sense to treat their removal as a fix.
I'd be interested to hear team's thoughts on how we should handle these unused types.
(Personally, I don't think these two types play an important role in the markdown plugins.)
=> fix: remove unused types from `types.ts`

package.json, src/types.ts
Simplify type definitions.
* Refactored the type definition of `MarkdownRuleDefinition` using the core [`CustomRuleDefinitionType`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L598-L631) type.
* Redefined `MarkdownRuleDefinitionTypeOptions` as an alias for the core [`CustomRuleTypeDefinitions`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L589-L596) type.
* Also upgraded `@eslint/core` to v0.15.
refs eslint/rewrite#177
Related PRs: eslint/eslint#19949, eslint/css#203, eslint/json#121
=> refactor: use `CustomRuleDefinitionType` in `MarkdownRuleDefinition`

src/rules/fenced-code-language.js, tests/rules/fenced-code-language.test.js
This pull request aims to enhance the clarity and precision of error reporting for the fenced-code-language rule. Previously, rule violations would highlight the entire code block, making it difficult to pinpoint the exact issue. This change ensures that only the relevant parts of the code are highlighted, improving the developer experience.
I've modified the fenced-code-language rule to provide more targeted highlighting for violations:
- For missing language errors, only the opening fences (e.g., ```) of the code block are now highlighted.
- For disallowed language errors, it will highlight the opening fence and the specified language.
Fixes #476
=> fix: fenced-code-language highlights only relevant parts

.github/workflows/add-to-triage.yml
Hi,
This PR is part of the process to centralize workflows. In this PR, I've added the `add-to-triage.yml` workflow, which uses the centralized workflow.
You can find more details about this workflow in https://github.com/eslint/workflows/issues/4 and https://github.com/eslint/workflows/pull/7.
=> ci: centralize `add-to-triage.yml`

src/rules/no-empty-definitions.js, tests/rules/no-empty-definitions.test.js
Enhance the `no-empty-definitions` rule to include identifier data in its verification process,  
ensuring more informative and accurate error messages.
- Updated `no-empty-definitions` rule logic to verify and expose identifier data.
- Added corresponding test cases in `no-empty-definitions.test.js` to cover new behavior.
- Ensured all existing tests pass.
refs #499
=> feat: expose identifiers in messages for no-empty-definitions

src/rules/no-duplicate-definitions.js, tests/rules/no-duplicate-definitions.test.js
This pull request updates the no-duplicate-definitions rule to include the specific identifier in its error messages. This change helps developers quickly locate the specific definition causing the issue.
- Updated the meta.messages of no-duplicate-definitions to include the {{ identifier }} placeholder.
- Updated the create function in the rule to pass the identifier through the data property in context.report().
- Updated the tests for the rule to verify that the identifier is correctly passed in invalid cases.
fixes #499
=> feat: Expose identifiers in messages for no-duplicate-definitions

src/rules/no-reversed-media-syntax.js
```markdown
Paragraph with `(label)[url]` reversed syntax.
```
The selector syntax: `"heading html,inlineCode"` is interpreted as:
- html inside heading
- OR any `inlineCode` node anywhere in the document
While in practice this behaves as intended since `inlineCode` can only appear inside headings, paragraphs, or table cells, the syntax can be misread and is less explicit about its scoping.
Selectors should clearly indicate that both `html` and `inlineCode` are matched only when nested within the relevant container node.
This PR fixes selector patterns to make their scope explicit and easier to read, replacing comma-separated selectors with `:matches()` expressions.
- Replaced comma-separated selectors such as `"heading html,inlineCode"` with :matches() expressions like `"heading …
=> refactor: correct no-reversed-media-syntax selectors

src/index.js, src/types.js, tests/types/types.test.ts
In this PR, I've exported all types from `src/types.ts` through the main entry point.
Previously, to access the global types defined in `src/types.ts`, they had to be imported from `@eslint/markdown/types`. After this change, they can be imported directly from `@eslint/markdown`.
To enable importing types from the main entry point, I used a small trick.
The `types.ts` file is built into `types.js` and `types.d.ts`.
In the built `types.js`, it's possible to re-export the type declarations from the main entry point using `export * from "types.js"`.
However, that wasn't possible in the source. To bridge the gap, I added a dummy `src/types.js` file so types can be imported from `src/types.ts`.
Ref: https://github.com/eslint/json/issues/130, …
=> feat: export types from main entry point

src/rules/no-reference-like-urls.js, tests/rules/no-reference-like-urls.test.js
CommonMark and GFM.
I've tried using consecutive backslashes in the `no-reference-like-urls` rule, but it reported false positives as shown below:
The code below doesn't report, which is the correct behavior.
```md
\[Mercury](mercury)
[mercury]: https://example.com/mercury
```
However, the code below does report, which are false positives:
```md
\\\[Mercury](mercury) 
\\\\\[Mercury](mercury) 
\\\\\\\[Mercury](mercury) 
[mercury]: https://example.com/mercury
```
The code below is reported as a `link` type, which is the correct behavior.
```md
\![Mercury](mercury)
[mercury]: https://example.com/mercury
```
However, The code below is reported as an `image` type, which are incorrect behaviors.
The code below should be reported as a `link` type, since the `!` is escaped with a backslash.
```md …
```
=> fix: handle consecutive backslashes in `no-reference-like-urls`

src/index.js, tests/types/tsconfig.json
In this PR, I’ve resolved the issue mentioned in #402.
I’ve confirmed that everything is working correctly by adding `exactOptionalPropertyTypes` to the tests and testing locally with a modified `index.d.ts` file.
The bug was caused by the type signature of `configs.processor`. The `configs.processor` type was showing an unintended type signature, which led to the issue.
For example, after removing `config.processor` from `index.d.ts` entirely, the type error no longer occurs.
---
Looking into it further, the issue was caused by the commented "key-value" pair below. If we comment out these "key-value" pairs, the error no longer occurs.
The commented-out "key-value" pairs above correspond to the JavaScript code below:
There were no `files?: undefined;`, `processor?: undefined;`, or similar …
=> fix: `exactOptionalPropertyTypes` causes type errors when using plugins

package.json, tests/package/exports.test.js, tests/types/tsconfig.json
To port the package exports test present in the other plugins into this repo for consistency and coverage.
- Added a new test suite for src/index.js exports.
- Update the `includes` pattern in `tests/types/tsconfig.json` to only include file with a `.test` suffix.
=> test: add package exports test

src/rules/no-multiple-h1.js
This PR originated from #536. While working on that, I found the scope had become too large, so I split this refactoring into a separate PR.
In this PR, I've used the native `getLocFromIndex` method added in #376 instead of the custom `findOffsets` util.
Notable changes:
- Replace the `findOffsets` util with the native `getLocFromIndex`.
- Use ESQuery selectors to reduce duplicated logic.
In this PR, I've used the native `getLocFromIndex` method added in #376 instead of the custom `findOffsets` util.
Ref: #376, #536
N/A
=> refactor: use `getLocFromIndex` in `no-multiple-h1`

src/rules/no-html.js
This PR originated from #536. While working on that, I found the scope had become too large, so I split this refactoring into a separate PR.
In this PR, I've used the native `getLocFromIndex` method added in #376 instead of the custom `findOffsets` util.
Notable changes:
- Replace the `findOffsets` util with the native `getLocFromIndex`.
- Use a named capture group in `htmlTagPattern` for better readability.
- Consolidate the tag-name normalization logic (`allowedIgnoreCase ? tagName.toLowerCase() : tagName`) into a single helper function, `normalizeTagName`.
- Remove the unnecessary `allowedElements.size === 0` check from the `if` clause when reporting.
In this PR, I've used the native `getLocFromIndex` method added in #376 instead of the custom `findOffsets` util.
Ref: #376, #536
N/A
=> refactor: use `getLocFromIndex` in `no-html`

src/util.js, tests/rules/no-multiple-h1.test.js, tests/rules/require-alt-text.test.js
Fixes report location in the `no-multiple-h1` and `require-alt-text` rules in cases where a preceding HTML comment has characters consisting of Unicode surrogate pairs.
Updated `utils.stripHtmlComments` to replace each code unit (instead of code point) with a space. This preserves offsets and locations of characters outside HTML comments.
=> fix: report locations in `no-multiple-h1` and `require-alt-text`

src/language/markdown-source-code.js, tests/types/types.test.ts
CommonMark and GFM.
I expected the return type of `applyInlineConfig().configs` — specifically `loc.start` and `loc.end` — to include an `offset` property, but they don't.
I expect the types of `loc.start` and `loc.end` to include an `offset` property.
```js
import { MarkdownSourceCode } from "./src/index.js";
const markdownSourceCode = new MarkdownSourceCode({
text: '',
ast: {
type: "root",
children: [
{
type: "html",
value: '',
position: {
start: {
line: 1,
column: 1,
offset: 0,
},
end: {
line: 1,
column: 42,
offset: 41,
},
},
},
],
position: {
start: {
line: 1,
column: 1,
offset: 0,
},
end: {
line: 1,
column: 42,
offset: 41,
},
},
},
});
console.log(markdownSourceCode.applyInlineConfig().configs[0].loc);
```
If you run the code above, you'll see that …
=> fix: correct the return type of `applyInlineConfig`
